# Generated by Django 5.1.6 on 2025-02-22 12:33

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electrohub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="debt",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.0"),
                default_currency="RUB",
                help_text="Укажите задолженность вашему поставщику",
                max_digits=14,
                verbose_name="Задолженность",
            ),
        ),
    ]
